"""Model checks for the Week 8 eight-step example (Step 8, Validate).

Run from the repository root with the project virtualenv:

    .venv/bin/python scripts/figures/week8_model_checks.py

Writes website/public/images/week8-model-checks.svg

Two simulated 50-minute records, both at an overall rate of 0.25 responses per
second. One is generated by the Poisson process the model assumes; the other is
generated by a two-state process (bouts of fast responding separated by pauses)
with the same overall rate, so the fitted lambda is identical and only the
diagnostics separate them.
"""

from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

OUT_DIR = Path(__file__).resolve().parents[2] / "website" / "public" / "images"

INK = "#0b0b0b"
AXIS = "#52514e"
ORANGE = "#eb6834"
PALE = "#b8b7b2"

plt.rcParams.update({
    "figure.facecolor": "white",
    "savefig.facecolor": "white",
    "font.size": 12,
    "axes.labelsize": 13,
    "axes.labelweight": "bold",
    "axes.labelcolor": INK,
    "axes.titlesize": 13,
    "axes.titleweight": "bold",
    "axes.titlecolor": INK,
    "axes.edgecolor": AXIS,
    "axes.linewidth": 1.1,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "xtick.color": AXIS,
    "ytick.color": AXIS,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "xtick.labelcolor": AXIS,
    "ytick.labelcolor": AXIS,
    "legend.fontsize": 10.5,
    "legend.frameon": False,
    "legend.labelcolor": AXIS,
    "svg.fonttype": "path",
})

LAM = 0.25          # responses per second, the rate estimated in the text
SESSION = 3000.0    # 50 minutes of steady-state performance
BIN = 60.0          # 1-minute bins for the count check

rng = np.random.default_rng(159)


def poisson_record():
    """Inter-response times drawn from the exponential the model assumes."""
    irts = rng.exponential(1 / LAM, size=1200)
    times = np.cumsum(irts)
    return times[times < SESSION]


def two_state_record():
    """Bouts of fast responding separated by pauses, same overall rate.

    A bout holds a mean of 5 responses at 1 response per second and is followed
    by a mean 15-s pause, so the record averages 5 responses per 20 s = 0.25/s.
    """
    times, t = [], 0.0
    while t < SESSION:
        for _ in range(1 + rng.poisson(4)):
            t += rng.exponential(1.0)
            times.append(t)
        t += rng.exponential(15.0)
    times = np.asarray(times)
    return times[times < SESSION]


def counts_per_bin(times):
    edges = np.arange(0, SESSION + BIN, BIN)
    return np.histogram(times, bins=edges)[0]


poisson_times = poisson_record()
burst_times = two_state_record()

fig, (ax_a, ax_b, ax_c) = plt.subplots(1, 3, figsize=(11.6, 3.7))

tau = np.linspace(0, 24, 400)
density = LAM * np.exp(-LAM * tau)
edges = np.arange(0, 24.5, 1.0)

for ax, times, color, title in (
    (ax_a, poisson_times, INK, "A.  Poisson process"),
    (ax_b, burst_times, ORANGE, "B.  Two-state responding"),
):
    irts = np.diff(times)
    ax.hist(irts, bins=edges, density=True, color=PALE, alpha=0.75,
            edgecolor=AXIS, linewidth=0.5)
    ax.plot(tau, density, color=color, linewidth=2.3)
    counts = counts_per_bin(times)
    ax.text(23.5, 0.425,
            f"counts per minute:\nmean {counts.mean():.1f}, "
            f"variance {counts.var(ddof=1):.1f}",
            fontsize=10, color=AXIS, ha="right", va="top", linespacing=1.5)
    ax.set_xlabel("Inter-response time, $\\tau$ (s)")
    ax.set_xlim(0, 24)
    ax.set_ylim(0, 0.44)
    ax.set_title(title, loc="left", pad=10)

ax_a.set_ylabel("Density")
ax_b.set_yticklabels([])

# --- Panel C: observed against theoretical exponential quantiles ---
probs = np.linspace(0.005, 0.995, 200)
theoretical = -np.log(1 - probs) / LAM
for times, color, marker, label in (
    (poisson_times, INK, "o", "Poisson process"),
    (burst_times, ORANGE, "^", "Two-state"),
):
    observed = np.quantile(np.diff(times), probs)
    ax_c.plot(theoretical, observed, linestyle="none", marker=marker,
              markersize=3.4, color=color, label=label)

ax_c.plot([0, 40], [0, 40], color=AXIS, linewidth=1.2, dashes=(4.8, 4.0))
ax_c.set_xlabel("Theoretical quantile (s)")
ax_c.set_ylabel("Observed quantile (s)")
ax_c.set_xlim(0, 26)
ax_c.set_ylim(0, 40)
ax_c.set_title("C.  Q-Q plot", loc="left", pad=10)
ax_c.legend(loc="upper left")

fig.tight_layout()
OUT_DIR.mkdir(parents=True, exist_ok=True)
fig.savefig(OUT_DIR / "week8-model-checks.svg", format="svg",
            bbox_inches="tight", pad_inches=0.15)
plt.close(fig)
print("wrote website/public/images/week8-model-checks.svg")
